--***---------------Jukit-----------------------***
vim.g.jukit_terminal = 'kitty'
--vim.g.jukit_layout = {
--  split= 'vertical',
--  p1= 0.7,
--  val = {
--    'file_content',
--    {
--      split= 'horizontal',
--      p1= 0.6,
--      val = {'output', 'output_history'}
--    }
--  }
--}
